### ISSUE TITLE
Clamd Conf Attribute Value Inconsistent between Linux Flavors

### ISSUE THREAD

**Issue by ajrpeggio** [geerlingguy/ansible-role-clamav#17]
Hello! I recently started testing out this role for ClamAV. So far I'm a fan as it's made the deployment as LOT easier.

I've noticed one thing during the creation / editing of the Configuration file when you use the "clamav_daemon_configuration_changes" variable.

I've noticed that Debian & RedHat flavors use different verbiage for their boolean value for some settings. Example:

Centos:
```
...
LogRotate yes
...
```

Ubuntu:
```
...
LogRotate true
...
```

If I set the variables for the role, I'll end up with consistent boolean attributes across both flavors. 

```yaml
---

- hosts: all
  tasks:
    - import_role:
        name: installed_clamav
      vars:
        clamav_daemon_configuration_changes:
          - regexp: '^.*LogRotate .*$'
            line: 'LocalSocket yes'
```

The vars set above will set this conf to "yes" for both flavors, even though debian flavors will require a "true" value.
